### ISSUE TITLE
create_function deprecated in php 7.2

### ISSUE THREAD

**Issue by webvitalii** [webvitalii/login-logout#2]
I see the following message when using the plugin with php 7.2:

Deprecated: Function create_function() is deprecated in /var/www/html/mafw.club/public_html/wp-content/plugins/login-logout/login-logout.php on line 251

https://wordpress.org/support/topic/create_function-deprecated-in-php-7-2-3/

**Comment by jeiseman** [comment]
Here's the change I made to fix the problem (in login-logout.php):

```
251c251,253
< add_action('widgets_init', create_function('', 'return register_widget("WP_Widget_Login_Logout");'));
---
> add_action('widgets_init', function() {
>     return register_widget("WP_Widget_Login_Logout");
> });
```

**Comment by webvitalii** [comment]
I fixed the issue. The update should be available vi WordPress admin panel.
@jeiseman  Thank you very much for your contribution. I mentioned you in the Changelog section https://github.com/webvitalii/login-logout/blob/master/readme.txt
